-- =============================================================================
-- Payer360 Demo: Populate Use-Case Marts from Fact/Dimension Joins
-- =============================================================================
-- Run as: SYSADMIN on P360_XFM_WH
-- Prerequisite: 05_mart_ddls.sql executed, all dims/facts populated (06, 07)
-- =============================================================================

USE ROLE SYSADMIN;
USE WAREHOUSE P360_XFM_WH;

-- =============================================================================
-- 1. MART_MEDICAL_LOSS_RATIO — MLR by LOB and month
-- Source: FCT_PREMIUM + DIM_LINE_OF_BUSINESS
-- =============================================================================
TRUNCATE TABLE IF EXISTS PAYER360_CUR.FINANCIAL.MART_MEDICAL_LOSS_RATIO;

INSERT INTO PAYER360_CUR.FINANCIAL.MART_MEDICAL_LOSS_RATIO
    (LOB_ID, LOB_NAME, MLR_THRESHOLD, PERIOD_DATE, PREMIUM_EARNED,
     INCURRED_CLAIMS, QUALITY_IMPROVEMENT_EXPENSE, ADMIN_EXPENSE,
     MLR_PCT, ADMIN_RATIO_PCT, IS_COMPLIANT, MEMBER_MONTHS)
SELECT
    lob.LOB_ID,
    lob.LOB_NAME,
    lob.MLR_THRESHOLD,
    fp.PREMIUM_MONTH AS PERIOD_DATE,
    SUM(fp.PREMIUM_EARNED) AS PREMIUM_EARNED,
    SUM(fp.INCURRED_CLAIMS_AMT) AS INCURRED_CLAIMS,
    SUM(fp.QUALITY_IMPROVEMENT_AMT) AS QUALITY_IMPROVEMENT_EXPENSE,
    SUM(fp.ADMIN_EXPENSE_AMT) AS ADMIN_EXPENSE,
    ROUND((SUM(fp.INCURRED_CLAIMS_AMT) + SUM(fp.QUALITY_IMPROVEMENT_AMT))
          / NULLIF(SUM(fp.PREMIUM_EARNED), 0) * 100, 2) AS MLR_PCT,
    ROUND(SUM(fp.ADMIN_EXPENSE_AMT)
          / NULLIF(SUM(fp.PREMIUM_EARNED), 0) * 100, 2) AS ADMIN_RATIO_PCT,
    (SUM(fp.INCURRED_CLAIMS_AMT) + SUM(fp.QUALITY_IMPROVEMENT_AMT))
          / NULLIF(SUM(fp.PREMIUM_EARNED), 0) * 100 >= lob.MLR_THRESHOLD * 100 AS IS_COMPLIANT,
    COUNT(*) AS MEMBER_MONTHS
FROM PAYER360_CUR.FINANCIAL.FCT_PREMIUM fp
JOIN PAYER360_CUR.FINANCIAL.DIM_LINE_OF_BUSINESS lob
    ON fp.LOB_SK = lob.LOB_SK
GROUP BY
    lob.LOB_ID, lob.LOB_NAME, lob.MLR_THRESHOLD, fp.PREMIUM_MONTH;

-- =============================================================================
-- 2. MART_CLAIMS_DENIALS — Claim detail with denial analysis
-- Source: FCT_CLAIM + DIM_MEMBER + DIM_PROVIDER + DIM_PROCEDURE_CPT
--         + DIM_DIAGNOSIS_ICD10 + DIM_PLAN + DIM_LINE_OF_BUSINESS
-- =============================================================================
TRUNCATE TABLE IF EXISTS PAYER360_CUR.CLAIMS.MART_CLAIMS_DENIALS;

INSERT INTO PAYER360_CUR.CLAIMS.MART_CLAIMS_DENIALS
    (CLAIM_ID, LINE_NUMBER, MEMBER_ID, MEMBER_NAME, PROVIDER_NPI, PROVIDER_NAME,
     SPECIALTY, SERVICE_DATE, SERVICE_MONTH, CHARGE_AMT, ALLOWED_AMT,
     DENIAL_REASON, DENIAL_CATEGORY, IS_DENIED, CLAIM_STATUS, IS_APPEALED,
     APPEAL_OUTCOME, LINE_OF_BUSINESS, PLAN_TYPE, CPT_CODE, CPT_DESCRIPTION,
     ICD10_CODE, DX_DESCRIPTION)
SELECT
    c.CLAIM_ID,
    c.LINE_NUMBER,
    m.MEMBER_ID,
    m.FIRST_NAME || ' ' || m.LAST_NAME AS MEMBER_NAME,
    p.NPI AS PROVIDER_NPI,
    p.FIRST_NAME || ' ' || p.LAST_NAME AS PROVIDER_NAME,
    p.SPECIALTY,
    c.SERVICE_DATE,
    DATE_TRUNC('MONTH', c.SERVICE_DATE) AS SERVICE_MONTH,
    c.CHARGE_AMT,
    c.ALLOWED_AMT,
    c.DENIAL_REASON,
    c.DENIAL_CATEGORY,
    c.IS_DENIED,
    c.CLAIM_STATUS,
    c.IS_APPEALED,
    c.APPEAL_OUTCOME,
    lob.LOB_NAME AS LINE_OF_BUSINESS,
    pl.PLAN_TYPE,
    cpt.CPT_CODE,
    cpt.DESCRIPTION AS CPT_DESCRIPTION,
    dx.ICD10_CODE,
    dx.DESCRIPTION AS DX_DESCRIPTION
FROM PAYER360_CUR.CLAIMS.FCT_CLAIM c
JOIN PAYER360_CUR.MEMBERSHIP.DIM_MEMBER m ON m.MEMBER_SK = c.MEMBER_SK
JOIN PAYER360_CUR.NETWORK.DIM_PROVIDER p ON p.PROVIDER_SK = c.PROVIDER_SK
LEFT JOIN PAYER360_CUR.CLAIMS.DIM_PROCEDURE_CPT cpt ON cpt.PROC_SK = c.PROC_SK
LEFT JOIN PAYER360_CUR.CLAIMS.DIM_DIAGNOSIS_ICD10 dx ON dx.DX_SK = c.DX_SK
JOIN PAYER360_CUR.MEMBERSHIP.DIM_PLAN pl ON pl.PLAN_SK = c.PLAN_SK
JOIN PAYER360_CUR.FINANCIAL.DIM_LINE_OF_BUSINESS lob ON lob.LOB_SK = c.LOB_SK;

-- =============================================================================
-- 3. MART_MEMBER_RENEWALS — Member retention and renewal analysis
-- Source: FCT_ENROLLMENT + DIM_MEMBER + DIM_PLAN + DIM_LINE_OF_BUSINESS
-- Filter: RENEW and TERM events
-- =============================================================================
TRUNCATE TABLE IF EXISTS PAYER360_CUR.MEMBERSHIP.MART_MEMBER_RENEWALS;

INSERT INTO PAYER360_CUR.MEMBERSHIP.MART_MEMBER_RENEWALS
    (MEMBER_ID, MEMBER_NAME, PLAN_ID, PLAN_NAME, PLAN_TYPE, LINE_OF_BUSINESS,
     EFFECTIVE_DATE, TERM_DATE, RENEWAL_FLAG, LAPSE_FLAG, TENURE_MONTHS,
     PREMIUM_MONTHLY, RISK_SCORE, AGE, GENDER, REGION)
SELECT
    m.MEMBER_ID,
    m.FIRST_NAME || ' ' || m.LAST_NAME AS MEMBER_NAME,
    pl.PLAN_ID,
    pl.PLAN_NAME,
    pl.PLAN_TYPE,
    lob.LOB_NAME AS LINE_OF_BUSINESS,
    e.EFFECTIVE_DATE,
    e.TERM_DATE,
    (e.EVENT_TYPE = 'RENEW') AS RENEWAL_FLAG,
    (e.EVENT_TYPE = 'TERM') AS LAPSE_FLAG,
    DATEDIFF(MONTH, m.ENROLLMENT_DATE, e.EVENT_DATE) AS TENURE_MONTHS,
    pl.MONTHLY_PREMIUM AS PREMIUM_MONTHLY,
    m.RISK_SCORE,
    DATEDIFF(YEAR, m.DOB, e.EVENT_DATE) AS AGE,
    m.GENDER,
    m.STATE AS REGION
FROM PAYER360_CUR.MEMBERSHIP.FCT_ENROLLMENT e
JOIN PAYER360_CUR.MEMBERSHIP.DIM_MEMBER m ON m.MEMBER_SK = e.MEMBER_SK
JOIN PAYER360_CUR.MEMBERSHIP.DIM_PLAN pl ON pl.PLAN_SK = e.PLAN_SK
JOIN PAYER360_CUR.FINANCIAL.DIM_LINE_OF_BUSINESS lob ON lob.LOB_SK = e.LOB_SK
WHERE e.EVENT_TYPE IN ('RENEW', 'TERM');

-- =============================================================================
-- 4. MART_MEMBER_SATISFACTION — NPS and CSAT with grievance correlation
-- Source: FCT_SURVEY + DIM_MEMBER + DIM_PLAN + DIM_LINE_OF_BUSINESS
--         + FCT_GRIEVANCE (correlated for grievance flag)
-- =============================================================================
TRUNCATE TABLE IF EXISTS PAYER360_CUR.MEMBER_EXPERIENCE.MART_MEMBER_SATISFACTION;

INSERT INTO PAYER360_CUR.MEMBER_EXPERIENCE.MART_MEMBER_SATISFACTION
    (SURVEY_ID, MEMBER_ID, MEMBER_NAME, SURVEY_DATE, SURVEY_MONTH,
     NPS_SCORE, NPS_CATEGORY, SATISFACTION_SCORE, TOPIC, PLAN_TYPE,
     LINE_OF_BUSINESS, IS_GRIEVANCE, RESOLUTION_DAYS, MEMBER_TENURE_MONTHS)
SELECT
    s.SURVEY_ID,
    m.MEMBER_ID,
    m.FIRST_NAME || ' ' || m.LAST_NAME AS MEMBER_NAME,
    s.SURVEY_DATE,
    DATE_TRUNC('MONTH', s.SURVEY_DATE) AS SURVEY_MONTH,
    s.NPS_SCORE,
    CASE
        WHEN s.NPS_SCORE <= 6 THEN 'Detractor'
        WHEN s.NPS_SCORE <= 8 THEN 'Passive'
        ELSE 'Promoter'
    END AS NPS_CATEGORY,
    s.SATISFACTION_SCORE,
    s.TOPIC,
    pl.PLAN_TYPE,
    lob.LOB_NAME AS LINE_OF_BUSINESS,
    EXISTS (
        SELECT 1 FROM PAYER360_CUR.MEMBER_EXPERIENCE.FCT_GRIEVANCE g
        WHERE g.MEMBER_SK = s.MEMBER_SK
          AND g.FILED_DATE BETWEEN DATEADD(DAY, -90, s.SURVEY_DATE) AND s.SURVEY_DATE
    ) AS IS_GRIEVANCE,
    (
        SELECT MAX(g.RESOLUTION_DAYS)
        FROM PAYER360_CUR.MEMBER_EXPERIENCE.FCT_GRIEVANCE g
        WHERE g.MEMBER_SK = s.MEMBER_SK
          AND g.FILED_DATE BETWEEN DATEADD(DAY, -90, s.SURVEY_DATE) AND s.SURVEY_DATE
    ) AS RESOLUTION_DAYS,
    DATEDIFF(MONTH, m.ENROLLMENT_DATE, s.SURVEY_DATE) AS MEMBER_TENURE_MONTHS
FROM PAYER360_CUR.MEMBER_EXPERIENCE.FCT_SURVEY s
JOIN PAYER360_CUR.MEMBERSHIP.DIM_MEMBER m ON m.MEMBER_SK = s.MEMBER_SK
JOIN PAYER360_CUR.MEMBERSHIP.DIM_PLAN pl ON pl.PLAN_SK = s.PLAN_SK
JOIN PAYER360_CUR.FINANCIAL.DIM_LINE_OF_BUSINESS lob ON lob.LOB_SK = s.LOB_SK;

-- =============================================================================
-- 5. MART_COMBINED_RATIO — Quarterly combined ratio by LOB
-- Source: FCT_PREMIUM + DIM_LINE_OF_BUSINESS
-- =============================================================================
TRUNCATE TABLE IF EXISTS PAYER360_CUR.FINANCIAL.MART_COMBINED_RATIO;

INSERT INTO PAYER360_CUR.FINANCIAL.MART_COMBINED_RATIO
    (LOB_ID, LOB_NAME, QUARTER_DATE, QUARTER_LABEL, PREMIUM_EARNED,
     INCURRED_LOSSES, LOSS_ADJUSTMENT_EXPENSE, UNDERWRITING_EXPENSE,
     LOSS_RATIO_PCT, EXPENSE_RATIO_PCT, COMBINED_RATIO_PCT,
     UNDERWRITING_RESULT, MEMBER_COUNT)
SELECT
    lob.LOB_ID,
    lob.LOB_NAME,
    DATE_TRUNC('QUARTER', fp.PREMIUM_MONTH) AS QUARTER_DATE,
    YEAR(fp.PREMIUM_MONTH)::STRING || '-Q' || QUARTER(fp.PREMIUM_MONTH)::STRING AS QUARTER_LABEL,
    SUM(fp.PREMIUM_EARNED) AS PREMIUM_EARNED,
    SUM(fp.INCURRED_CLAIMS_AMT) AS INCURRED_LOSSES,
    -- Loss adjustment expense approximated as 5% of incurred
    ROUND(SUM(fp.INCURRED_CLAIMS_AMT) * 0.05, 2) AS LOSS_ADJUSTMENT_EXPENSE,
    SUM(fp.ADMIN_EXPENSE_AMT) AS UNDERWRITING_EXPENSE,
    ROUND(SUM(fp.INCURRED_CLAIMS_AMT)
          / NULLIF(SUM(fp.PREMIUM_EARNED), 0) * 100, 2) AS LOSS_RATIO_PCT,
    ROUND((SUM(fp.ADMIN_EXPENSE_AMT) + SUM(fp.INCURRED_CLAIMS_AMT) * 0.05)
          / NULLIF(SUM(fp.PREMIUM_EARNED), 0) * 100, 2) AS EXPENSE_RATIO_PCT,
    ROUND((SUM(fp.INCURRED_CLAIMS_AMT) + SUM(fp.ADMIN_EXPENSE_AMT) + SUM(fp.INCURRED_CLAIMS_AMT) * 0.05)
          / NULLIF(SUM(fp.PREMIUM_EARNED), 0) * 100, 2) AS COMBINED_RATIO_PCT,
    ROUND(SUM(fp.PREMIUM_EARNED) - SUM(fp.INCURRED_CLAIMS_AMT) - SUM(fp.ADMIN_EXPENSE_AMT)
          - SUM(fp.INCURRED_CLAIMS_AMT) * 0.05, 2) AS UNDERWRITING_RESULT,
    COUNT(DISTINCT fp.MEMBER_SK) AS MEMBER_COUNT
FROM PAYER360_CUR.FINANCIAL.FCT_PREMIUM fp
JOIN PAYER360_CUR.FINANCIAL.DIM_LINE_OF_BUSINESS lob
    ON fp.LOB_SK = lob.LOB_SK
GROUP BY
    lob.LOB_ID, lob.LOB_NAME,
    DATE_TRUNC('QUARTER', fp.PREMIUM_MONTH),
    YEAR(fp.PREMIUM_MONTH)::STRING || '-Q' || QUARTER(fp.PREMIUM_MONTH)::STRING;

-- =============================================================================
-- 6. MART_CLAIMS_SETTLEMENT — Claims processing cycle times
-- Source: FCT_CLAIM + DIM_MEMBER + DIM_PROVIDER + DIM_PLAN + DIM_LINE_OF_BUSINESS
-- =============================================================================
TRUNCATE TABLE IF EXISTS PAYER360_CUR.CLAIMS.MART_CLAIMS_SETTLEMENT;

INSERT INTO PAYER360_CUR.CLAIMS.MART_CLAIMS_SETTLEMENT
    (CLAIM_ID, MEMBER_ID, MEMBER_NAME, PROVIDER_NPI, PROVIDER_NAME,
     SERVICE_DATE, RECEIVED_DATE, ADJUDICATED_DATE, PAID_DATE,
     DAYS_TO_ADJUDICATE, DAYS_TO_PAY, TOTAL_CYCLE_DAYS,
     IS_CLEAN_CLAIM, IS_AUTO_ADJUDICATED, CLAIM_STATUS,
     CHARGE_AMT, PAID_AMT, LINE_OF_BUSINESS, PLAN_TYPE)
SELECT
    c.CLAIM_ID,
    m.MEMBER_ID,
    m.FIRST_NAME || ' ' || m.LAST_NAME AS MEMBER_NAME,
    p.NPI AS PROVIDER_NPI,
    p.FIRST_NAME || ' ' || p.LAST_NAME AS PROVIDER_NAME,
    c.SERVICE_DATE,
    c.RECEIVED_DATE,
    c.ADJUDICATED_DATE,
    c.PAID_DATE,
    DATEDIFF(DAY, c.RECEIVED_DATE, c.ADJUDICATED_DATE) AS DAYS_TO_ADJUDICATE,
    DATEDIFF(DAY, c.ADJUDICATED_DATE, c.PAID_DATE) AS DAYS_TO_PAY,
    DATEDIFF(DAY, c.RECEIVED_DATE, COALESCE(c.PAID_DATE, c.ADJUDICATED_DATE)) AS TOTAL_CYCLE_DAYS,
    c.IS_CLEAN_CLAIM,
    c.IS_AUTO_ADJUDICATED,
    c.CLAIM_STATUS,
    c.CHARGE_AMT,
    c.PAID_AMT,
    lob.LOB_NAME AS LINE_OF_BUSINESS,
    pl.PLAN_TYPE
FROM PAYER360_CUR.CLAIMS.FCT_CLAIM c
JOIN PAYER360_CUR.MEMBERSHIP.DIM_MEMBER m ON m.MEMBER_SK = c.MEMBER_SK
JOIN PAYER360_CUR.NETWORK.DIM_PROVIDER p ON p.PROVIDER_SK = c.PROVIDER_SK
JOIN PAYER360_CUR.MEMBERSHIP.DIM_PLAN pl ON pl.PLAN_SK = c.PLAN_SK
JOIN PAYER360_CUR.FINANCIAL.DIM_LINE_OF_BUSINESS lob ON lob.LOB_SK = c.LOB_SK;

-- =============================================================================
-- 7. MART_PROVIDER_NETWORK — Provider network health and turnover
-- Source: FCT_PROVIDER_CONTRACT + DIM_PROVIDER + DIM_REGION
-- =============================================================================
TRUNCATE TABLE IF EXISTS PAYER360_CUR.NETWORK.MART_PROVIDER_NETWORK;

INSERT INTO PAYER360_CUR.NETWORK.MART_PROVIDER_NETWORK
    (PROVIDER_NPI, PROVIDER_NAME, SPECIALTY, PRACTICE_NAME, REGION_NAME,
     CONTRACT_START, CONTRACT_END, IS_ACTIVE, IS_TERMINATED, TERMINATION_REASON,
     CONTRACT_YEARS, CLAIMS_VOLUME, MEMBER_PANEL_SIZE, QUALITY_SCORE, TENURE_YEARS)
SELECT
    p.NPI AS PROVIDER_NPI,
    p.FIRST_NAME || ' ' || p.LAST_NAME AS PROVIDER_NAME,
    p.SPECIALTY,
    p.PRACTICE_NAME,
    r.REGION_NAME,
    pc.CONTRACT_START,
    pc.CONTRACT_END,
    pc.IS_ACTIVE,
    pc.IS_TERMINATED,
    pc.TERMINATION_REASON,
    ROUND(DATEDIFF(DAY, pc.CONTRACT_START, COALESCE(pc.CONTRACT_END, CURRENT_DATE())) / 365.25, 1) AS CONTRACT_YEARS,
    pc.CLAIMS_VOLUME,
    pc.MEMBER_PANEL_SIZE,
    pc.QUALITY_SCORE,
    ROUND(DATEDIFF(DAY, pc.CONTRACT_START, COALESCE(pc.CONTRACT_END, CURRENT_DATE())) / 365.25, 1) AS TENURE_YEARS
FROM PAYER360_CUR.NETWORK.FCT_PROVIDER_CONTRACT pc
JOIN PAYER360_CUR.NETWORK.DIM_PROVIDER p ON p.PROVIDER_SK = pc.PROVIDER_SK
JOIN PAYER360_CUR.NETWORK.DIM_REGION r ON r.REGION_SK = pc.REGION_SK;
